version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://dynamic_user:dynamic_pass@db:5432/dynamic_servers
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-change-this}
      - HETZNER_API_TOKEN=${HETZNER_API_TOKEN}
      - FLASK_ENV=production
      - REPL_ID=${REPL_ID:-dynamic-servers}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mount SSH keys if they exist locally
      - ~/.ssh:/root/.ssh:ro
    restart: unless-stopped
    networks:
      - dynamic-servers

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dynamic_servers
      - POSTGRES_USER=dynamic_user
      - POSTGRES_PASSWORD=dynamic_pass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dynamic_user -d dynamic_servers"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - dynamic-servers

  # Optional: Redis for session storage (if needed in future)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - dynamic-servers

volumes:
  postgres_data:

networks:
  dynamic-servers:
    driver: bridge